server:
  port: 1000
spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Laojunge0825/spring-cloud-config.git
          username: Laojunge0825
          password: pcj254779
          search-paths: config-center
      label: master
#  profiles:
#    active: native
Eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka,http://127.0.0.1:8002/eureka,http://127.0.0.1:8003/eureka